services:
  elastic-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=dark-cluster
      - xpack.security.enabled=false
      
    networks:
      - service-network
      
  kibana-service:
    image: docker.elastic.co/kibana/kibana:7.15.0
    restart: unless-stopped
    ports:
      - "80:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-service:9200
      - KIBANA_AUTOCOMPLETETIMEOUT=45000
      - KIBANA_AUTOCOMPLETETERMINATEAFTER=999999
      - KIBANA_TELEMETRYENABLED=false
    networks:
      - service-network
      
networks:
  service-network:    
    driver: bridge
